FPS = 60
WIDTH = 640     # display size width
HEIGHT = 640    # display size height
TILESIZE = 32
BOARD_ORIGIN_X = 0
BOARD_ORIGIN_Y = 0
COLS = 10                       # number of columns in the board
BOARD_WIDTH = COLS * TILESIZE   # board size width
ROWS = 10                       # number of rows in the board
BOARD_HEIGHT = ROWS * TILESIZE  # baord size height
